name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  # publish-npm任务
  release-when-tag-change:
    # 在ubuntu最新版本的虚拟机执行
    runs-on: ubuntu-latest
    # 设置变量
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # 检查并切换到master分支
      - name: 检查master分支
        # 使用actions/checkout插件
        uses: actions/checkout@master

      # 安装node
      - name: 设置Node.js
        # 使用actions/setup-node插件
        uses: actions/setup-node@master
        with:
          # node版本
          node-version: ${{ matrix.node-version }}

      - name: 设置pnpm
        uses: pnpm/action-setup@v2

      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./packages/toy-design/package.json
          property: version

      - name: 发布NPM包
        # 执行发布代码
        run: sh ./scripts/publish.sh
        env:
          # 配置 npm access token 环境变量
          NPM_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
          REGISTRY: https://registry.npmjs.com/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 创建GitHub Release
      - name: 创建GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          # 配置github token （这个无需去github配置，默认存在的）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 标签名
          tag_name: v${{steps.version.outputs.value}}
          # release名
          release_name: v${{steps.version.outputs.value}}
          # 是否为草稿
          draft: false
          # 是否为预发布
          prerelease: false
